import re
import json
import os

def remove_coordinates(js_paths):
    for js_path in js_paths:
        try:
            with open(js_path, 'r') as js_file:
                js_data = js_file.read()

                # Extract the JSON part from the JavaScript file using regex
                match = re.search(r'\{.*\}', js_data, re.DOTALL)
                if match:
                    json_data = match.group(0)
                    data = json.loads(json_data)

                    # Loop through features and remove coordinates
                    for feature in data["features"]:
                        if "geometry" in feature and "coordinates" in feature["geometry"]:
                            feature["geometry"]["coordinates"] = []

                    # Write the modified data back to the JavaScript file
                    with open(js_path, 'w') as js_file:
                        js_file.write("var data = ")
                        json.dump(data, js_file, indent=2)
                        js_file.write(";")
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON in file {js_path}: {e}")
            continue

# Example usage with multiple files
js_paths = [
"EmptyTracks/Xomo.js",
"EmptyTracks/Xon.js",
"EmptyTracks/Zambla.js",
"EmptyTracks/Zeno.js",
"EmptyTracks/Zoncolan.js",
"EmptyTracks/Zovo.js",
"EmptyTracks/Achenpass.js",
"EmptyTracks/Ächerli.js",
"EmptyTracks/Agnel.js",
"EmptyTracks/Agueglio.js",
"EmptyTracks/Albula.js",
"EmptyTracks/Allos.js",
"EmptyTracks/AmmerSattel.js",
"EmptyTracks/Antonio.js",
"EmptyTracks/Aprica.js",
"EmptyTracks/Arlberg.js",
"EmptyTracks/ÄulemerKreuz.js",
"EmptyTracks/Aune.js",
"EmptyTracks/Avena.js",
"EmptyTracks/Balisio.js",
"EmptyTracks/Berbenno.js",
"EmptyTracks/Bernardino.js",
"EmptyTracks/Bernina.js",
"EmptyTracks/Bieler.js",
"EmptyTracks/Boldo.js",
"EmptyTracks/Bonette.js",
"EmptyTracks/BonetteCime.js",
"EmptyTracks/Borcola.js",
"EmptyTracks/Bordala.js",
"EmptyTracks/Brandenberg.js",
"EmptyTracks/Brennero.js",
"EmptyTracks/Brianza.js",
"EmptyTracks/Brocon.js",
"EmptyTracks/Buchener.js",
"EmptyTracks/Bura.js",
"EmptyTracks/CampoCarloMagno.js",
"EmptyTracks/Campolongo.js",
"EmptyTracks/Cereda.js",
"EmptyTracks/Champex.js",
"EmptyTracks/Champs.js",
"EmptyTracks/Coe.js",
"EmptyTracks/ColDeLaCroix.js",
"EmptyTracks/Crocedomini.js",
"EmptyTracks/CroixDeCoeur.js",
"EmptyTracks/CroixDeFer.js",
"EmptyTracks/Culmine.js",
"EmptyTracks/Dientner.js",
"EmptyTracks/Dresselbach.js",
"EmptyTracks/Duft.js",
"EmptyTracks/Duran.js",
"EmptyTracks/Dürreck.js",
"EmptyTracks/Echelle.js",
"EmptyTracks/Edelweiss.js",
"EmptyTracks/Eira.js",
"EmptyTracks/Eisentalhöhe.js",
"EmptyTracks/Ellegg.js",
"EmptyTracks/Erbe.js",
"EmptyTracks/ErlerBerg.js",
"EmptyTracks/Esischie.js",
"EmptyTracks/Falzarego.js",
"EmptyTracks/Faschinajoch.js",
"EmptyTracks/Fauniera.js",
"EmptyTracks/Fedaia.js",
"EmptyTracks/Feldbergpass.js",
"EmptyTracks/Fernpass.js",
"EmptyTracks/Finestre.js",
"EmptyTracks/Fittanze.js",
"EmptyTracks/Flexen.js",
"EmptyTracks/Fluela.js",
"EmptyTracks/Forcora.js",
"EmptyTracks/Foscagno.js",
"EmptyTracks/Fugazze.js",
"EmptyTracks/Fuipiano.js",
"EmptyTracks/Furcia.js",
"EmptyTracks/Furka.js",
"EmptyTracks/Furkajoch.js",
"EmptyTracks/Fürsatzhöhe.js",
"EmptyTracks/Gaichtpass.js",
"EmptyTracks/Galibier.js",
"EmptyTracks/Gampen.js",
"EmptyTracks/Ganda.js",
"EmptyTracks/Gardena.js",
"EmptyTracks/Gavia.js",
"EmptyTracks/Gerlos.js",
"EmptyTracks/Ghisallo.js",
"EmptyTracks/Giau.js",
"EmptyTracks/Glandon.js",
"EmptyTracks/Glaubenberg.js",
"EmptyTracks/Glaubenbielen.js",
"EmptyTracks/Glockner.js",
"EmptyTracks/Gobbera.js",
"EmptyTracks/Gottardo.js",
"EmptyTracks/Grän.js",
"EmptyTracks/GranBernard.js",
"EmptyTracks/Grappa.js",
"EmptyTracks/Grimsel.js",
"EmptyTracks/Gschütt.js",
"EmptyTracks/Guspessa.js",
"EmptyTracks/Hahntennjoch.js",
"EmptyTracks/Hirschbichl.js",
"EmptyTracks/Hochschwarzeck.js",
"EmptyTracks/Hochtannberg.js",
"EmptyTracks/Hohtann.js",
"EmptyTracks/Huez.js",
"EmptyTracks/Ibergeregg.js",
"EmptyTracks/Irschenberg.js",
"EmptyTracks/Iselsberg.js",
"EmptyTracks/Iseran.js",
"EmptyTracks/Izoard.js",
"EmptyTracks/Jaufen.js",
"EmptyTracks/Jaun.js",
"EmptyTracks/JouxVerte.js",
"EmptyTracks/Julier.js",
"EmptyTracks/KaiserFranzJosef.js",
"EmptyTracks/Kandel.js",
"EmptyTracks/Karer.js",
"EmptyTracks/Kaunertal.js",
"EmptyTracks/Kerschbaumer.js",
"EmptyTracks/KitzHorn.js",
"EmptyTracks/Klausen.js",
"EmptyTracks/Kreuzweg.js",
"EmptyTracks/Kühtai.js",
"EmptyTracks/Larche.js",
"EmptyTracks/Lautaret.js",
"EmptyTracks/Lavaze.js",
"EmptyTracks/Lein.js",
"EmptyTracks/Lienbachsattel.js",
"EmptyTracks/Livigno.js",
"EmptyTracks/Lombarde.js",
"EmptyTracks/Losenpass.js",
"EmptyTracks/Loze.js",
"EmptyTracks/Lukmanier.js",
"EmptyTracks/Lys.js",
"EmptyTracks/Madeleine.js",
"EmptyTracks/Madonnina.js",
"EmptyTracks/Maloja.js",
"EmptyTracks/Manghen.js",
"EmptyTracks/Maniva.js",
"EmptyTracks/Marco.js",
"EmptyTracks/Marzio.js",
"EmptyTracks/Mendola.js",
"EmptyTracks/Miragolo.js",
"EmptyTracks/MontCenis.js",
"EmptyTracks/Montecampione.js",
"EmptyTracks/Montets.js",
"EmptyTracks/Montevecchia.js",
"EmptyTracks/Montgenevre.js",
"EmptyTracks/Moosalp.js",
"EmptyTracks/Mortirolo.js",
"EmptyTracks/Narro.js",
"EmptyTracks/Nassfeld.js",
"EmptyTracks/Neggia.js",
"EmptyTracks/Nespello.js",
"EmptyTracks/Niederndorfer.js",
"EmptyTracks/Niger.js",
"EmptyTracks/Nivolet.js",
"EmptyTracks/Notschrei.js",
"EmptyTracks/Nufenen.js",
"EmptyTracks/Oberalp.js",
"EmptyTracks/Oberjoch.js",
"EmptyTracks/Ofen.js",
"EmptyTracks/Pellegrino.js",
"EmptyTracks/PenserJoch1.js",
"EmptyTracks/PetitBernard.js",
"EmptyTracks/Pillon.js",
"EmptyTracks/Planches.js",
"EmptyTracks/Ploecken.js",
"EmptyTracks/Pordoi.js",
"EmptyTracks/Pragel.js",
"EmptyTracks/Pré.js",
"EmptyTracks/Predil.js",
"EmptyTracks/Presolana.js",
"EmptyTracks/Primo.js",
"EmptyTracks/Reschen.js",
"EmptyTracks/Rettenbachferner.js",
"EmptyTracks/Riedberg.js",
"EmptyTracks/Rinken.js",
"EmptyTracks/Rohrmoos.js",
"EmptyTracks/Rolle.js",
"EmptyTracks/Roncola.js",
"EmptyTracks/Roselend.js",
"EmptyTracks/Rossfeld.js",
"EmptyTracks/RotesKreuz.js",
"EmptyTracks/Salmezza.js",
"EmptyTracks/Samerberg.js",
"EmptyTracks/Sampeyre.js",
"EmptyTracks/SanBarbara.js",
"EmptyTracks/SantaBarbara.js",
"EmptyTracks/Sarenne.js",
"EmptyTracks/Sattelegg.js",
"EmptyTracks/Schauinsland.js",
"EmptyTracks/Scheidegg.js",
"EmptyTracks/Schiestlscharte.js",
"EmptyTracks/Seefeld.js",
"EmptyTracks/Sella.js",
"EmptyTracks/Selvino.js",
"EmptyTracks/Sestriere.js",
"EmptyTracks/Simplon.js",
"EmptyTracks/Soelk.js",
"EmptyTracks/Sommo.js",
"EmptyTracks/Sormano.js",
"EmptyTracks/Spitzing.js",
"EmptyTracks/Splugen.js",
"EmptyTracks/Staller.js",
"EmptyTracks/Staulanza.js",
"EmptyTracks/Stelvio.js",
"EmptyTracks/Sudelfeld.js",
"EmptyTracks/Susten.js",
"EmptyTracks/Tedesco.js",
"EmptyTracks/Telegraphe.js",
"EmptyTracks/Tende.js",
"EmptyTracks/Thurn.js",
"EmptyTracks/Tiefenbachferner.js",
"EmptyTracks/Timmelsjoch.js",
"EmptyTracks/Toerwang.js",
"EmptyTracks/Tonale.js",
"EmptyTracks/TorriFraele.js",
"EmptyTracks/TreCime.js",
"EmptyTracks/TreCroci.js",
"EmptyTracks/Trivigno.js",
"EmptyTracks/Turini.js",
"EmptyTracks/Umbrail.js",
"EmptyTracks/Ursprung.js",
"EmptyTracks/Valbrona.js",
"EmptyTracks/Valcava.js",
"EmptyTracks/Valles.js",
"EmptyTracks/Valmara.js",
"EmptyTracks/Valparola.js",
"EmptyTracks/Valvarrone.js",
"EmptyTracks/Vars.js",
"EmptyTracks/Ventoux.js",
"EmptyTracks/Vezzena.js",
"EmptyTracks/Vivione.js",
"EmptyTracks/Walleralm.js",
"EmptyTracks/Weissenbachsattel.js",
"EmptyTracks/WidiwanderEck.js",
"EmptyTracks/Wolfgang.js"]
remove_coordinates(js_paths)